# -*- coding: utf-8 -*-
"""poem_ai_bot.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zi7zY6gCQKtguehRkV4IC9UTGcK4KPtn
"""

import numpy as np
import pickle

model = pickle.load(open('model_pkl_700_100_50k', 'rb'))
char_to_id = pickle.load(open('char_to_id-2.pkl', 'rb'))
id_to_char = pickle.load(open('id_to_char-2.pkl', 'rb'))

n_chars = 47
train_length = 100

string = ''
while True:
    print('Walt Whitbot: Let me recite a poem. Just give me a phrase...\n')
    string = input('You: ')
    if string=='quit':
        break
    bot_poem = list(string.lower()+' ')
    bot_poem_vector = [char_to_id[char] for char in bot_poem]
    bot_poem_vector +=  [1]*(100-len(bot_poem_vector))
    char_limit = 150
    for i in range(char_limit):
        botx = np.array(bot_poem_vector).reshape(1,train_length,1)
        botx = botx/n_chars
        pred_ind = np.argmax(model.predict(botx, verbose=0))
        pred_char = id_to_char[pred_ind]
        bot_poem_vector.append(pred_ind)
        bot_poem.append(pred_char)
        bot_poem_vector = bot_poem_vector[1:]
    bot_poem_finish = "".join(bot_poem)+'\n\n'
    print('Walt Whitbot: ', bot_poem_finish)
    print('Walt Whitbot: Did you understand my masterpiece?\n')
    response = input('You: ').lower()
    if response == 'yes':
        print('Walt Whitbot: I see you speak the language of the gods\n')
    if response == 'no':
        print('Walt Whitbot: Your measly intellect fails to appeciate the beauty in those words\n')
    print('Walt Whitbot: Do you wish upon another verse? \n')
    string = input('You: ').lower()
    if string == 'no' or string == 'quit':
        print('Walt Whitbot: Until next time.. \n')
        break
